Appointments/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.app_one.urls', namespace="app1")),
    url(r'^app2/', include('apps.app_two.urls', namespace="app2")),
    url(r'^admin/', admin.site.urls),
]

apps/app_one/urls.py
from django.conf.urls import url, include
from . import views

# This is app_one
urlpatterns = [
# root route to index method
    url(r'^$', views.index),
    url(r'^main$', views.index, name='index'),
    url(r'^login$', views.login, name='login'),
    url(r'^register$', views.register, name='register'),
    url(r'^logout$', views.logout, name='logout'),

]

apps/app_one/models.py
from __future__ import unicode_literals
from django.db import models
from datetime import datetime, date
#importing regex
import re, bcrypt
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

# Create your models here.
# Handle logic in the model
# View page will call model method, which is built into the model manager class
class UserManager(models.Manager):
# method to handle user validations
# post_data is the information from request.POST
    def validate_user(self, post_data):
        # dictionary to contain user data from models.py
        response_to_views = {}
        # list to gather up errors:
        errors = []
        print("In model method:", post_data)

        # add validations:
        # Note: This part is often the source of multi-dict key errors
# name
        if not post_data['name']:#python returns an empty string as false
            errors.append('Name is required')
        if not len(post_data['name']) >= 5:
            errors.append('Name must be at least 5 characters')

# alias
        if not post_data['alias']:#python returns an empty string as false
            errors.append('Alias is required')
        if not len(post_data['alias']) >= 2:
            errors.append('Alias must be at least 2 characters')
        # isalpha checks that string contains only letters:

# email
        # sends post_data into regex to be checked for match
        if not EMAIL_REGEX.match(post_data['email']):
            errors.append('Enter a valid email')

# password
        if len(post_data['password']) < 8:
            errors.append('Password must be at least 8 characters')
        if not post_data['password'] == post_data['confirmPW']:
            errors.append('Passwords must match')

# date of birth; date object from datetime changed to string:
        if not post_data['dob'] < str(date.today()):
            datestring = str(date.today())
            print("Datestring is:", datestring)
            errors.append("Your date of birth cannot be in the future")
        if not post_data['dob']:
            errors.append("Please enter a date of birth")

# check that submitted email is unique (non-duplicate) before other validations, because users log in with their emails
# filter will return false if list is empty, true if not empty
        if self.filter(email = post_data['email']):
            errors.append('Email is already in use')

# checking the errors for failed validations
# if any validations fail, user cannot be logged in
# error messages will be returned
# status and errors are keys in the dictionary response_to_views
        if errors: #failed validations
            response_to_views['status'] = False
            response_to_views['errors'] = errors
        else: #passed validations
            response_to_views['status'] = True

            #hash the password with bcrypt
            hashed_password = bcrypt.hashpw(post_data['password'].encode(), bcrypt.gensalt())

            #create new user, saves data in a variable (user):
            user = self.create(name = post_data['name'], alias = post_data['alias'], email = post_data['email'], password = hashed_password, dob = post_data['dob'])
            # user object is saved as a key in list and returned:
            response_to_views['user'] = user
#return response data
        return response_to_views

# finding a user in the database with the user's email:
    def login_user(self, post_data):
        print("This is login_user method in models.py")
        #will be true if email found, false if it isn't:
        response_to_views = {}
        #filter will return only 1 object & won't generate error if email doesn't exist
        user = self.filter(email = post_data['email'])
        print("User:", user)

        if user:#if user email is in the database:
# checks whether submitted password matches one in the database
# submitted pw is hashed with same formula as db password
# because filter returns only 1 object at a time, the user is always user[0]
# bcrypt.checkpw returns a boolean, true or false
            if bcrypt.checkpw(post_data['password'].encode(), user[0].password.encode()):#if boolean is true:
            # user object is saved in response_to_views
                response_to_views['status'] = True
                response_to_views['user'] = user[0]#will be returned & saved in session

            else:#if password is invalid
                response_to_views['status'] = False
                response_to_views['errors'] = "Invalid email/password combination"

        else:#if user email is not found in database:
            response_to_views['status'] = False
            response_to_views['errors'] = "Invalid email"

#return response data
        return response_to_views


class User(models.Model):
    name=models.CharField(max_length=45)
    alias=models.CharField(max_length=45)
    email=models.CharField(max_length=100)
    password=models.CharField(max_length=25)
    dob=models.DateField(default=datetime.today, blank=True)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

# links UserManager to User, by overwriting the objects hidden key that all models have
    objects = UserManager()

apps/app_one/views.py
from django.shortcuts import render, HttpResponse, redirect
# links model to view functions
from .models import User
# allows flash messages to html
from django.contrib import messages

# Note: Registration and login validations are done in models.py

# displays a form on index.html for users to enter login or registration info
def index(request):
    print("This is index function in app_one views.py")
    return render(request, 'app_one/index.html')


# logs in user if validations are met
def login(request):
    print("This is login function in app_one views.py")
    # saves user POST data from models method login_user in response_from_models:
    response_from_models = User.objects.login_user(request.POST)
    print("Response from models:", response_from_models)
    if response_from_models['status']:#if true (validations are met):
        #saves user data in session, sends user to success page:
        request.session['user_id'] = response_from_models['user'].id
        request.session['user_alias'] = response_from_models['user'].alias
        return redirect('app2:index')
    else:#returns user to index.html, displays error message:
        messages.error(request, response_from_models['errors'])
        return redirect('app1:index')


# saves a user object if registration validations are met
def register(request):
    print("This is register function in app_one views.py")
    # this checks that users have submitted form data before proceeding to register route
    if request.method == 'POST':
        print("Request.POST:", request.POST)
        # invokes validations method from the model manager
        # saves user data from models.py in a variable
        # whatever is sent back in the UserManager return statement
        response_from_models = User.objects.validate_user(request.POST)
        print("Response from models:", response_from_models)
        if response_from_models['status']:#if true
            # passed the validations and created a new user
            # user can now be saved in session, by id:
            # index method in app_two will use this:
            request.session['user_id'] = response_from_models['user'].id
            request.session['user_alias'] = response_from_models['user'].alias
            print("App1 alias:", request.session['user_alias'])
#redirects to index method in 2nd app via named route app2 from project-level urls.py
            return redirect('app2:index')#named route/views.py method
# 1st app handles only logging in / registering users
        else:
            # add flash messages to html:
            for error in response_from_models['errors']:
                messages.error(request, error)
            # returns to index.html via named route app1, index method in views.py
            return redirect('app1:index')

    # if not POST, redirects to index method via named route namespace=app1
    else:
        return redirect('app1:index')


def logout (request):
    request.session.clear()#deletes everything in session
    return redirect('app1:index')

apps/app_one/templates/app_one/index.html
<!DOCTYPE html>
<html>
  <head>
    <title>Login and Registration</title>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'app_one/css/style.css' %}" media="screen" title="no title">

  </head>
  <body>
    <!-- <h1>This is index.html in apps_one</h1> -->
    <fieldset>
    <!-- <div class="wrapper"> -->
      <div class="registration">
        <!-- <form action="/register" method="POST" id="register"> -->

          <!-- This is the python syntax used with named routes: -->
          <!-- register is a named route in apps-level urls.py -->
        <form class="" action="{% url 'app1:register' %}" method="POST">
          {% csrf_token %}

          <h1>Registration</h1>
          <h3>Name: <input type="text" name="name" value=""></h3>
          <h3>Alias: <input type="text" name="alias" value=""></h3>
          <h3>Email: <input type="text" name="email" value=""></h3>
          <!-- type="password" hides the password -->
          <h3>Password: <input type="password" name="password" value=""></h3>
          <h3>Confirm Password: <input type="password" name="confirmPW" value=""></h3>
          <!-- type="date" generates a datepicker -->
          <h3>Date of Birth: <input type="date" name="dob" value=""></h3>
          <input type="Submit" value="Register">
          <br>
          <br>
        </form>
      </div><!-- end of registration -->
    </fieldset>

    <fieldset>
<!-- trying to make the error messages print out in red; haven't succeeded yet -->
      <div class="error_messages">
<!-- displaying error messages -->
        {% if messages %}
          <ul class="messages">
            {% for message in messages %}
              <li>{{ message }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>

      <div class="login">
        <!-- <form action="/login" method="POST"> -->
        <!-- This is the python syntax used with named routes: -->
        <!-- app1 is the named route for app_one in main-level urls.py -->
        <!-- register is a named route in apps-level urls.py -->
        <form class="" action="{% url 'app1:login' %}" method="POST">
          {% csrf_token %}

          <h1>Log in</h1>
          <h3>Email: <input type="text" name="email" value=""></h3>
          <h3>Password: <input type="password" name="password" value=""></h3>
          <input type="Submit" value="Login">
          <br>
          <br>
        </form>
      </div>

    </fieldset>
    <!-- </div> wrapper end div-->
  </body>
</html>