Appointments/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.app_one.urls', namespace="app1")),
    url(r'^app2/', include('apps.app_two.urls', namespace="app2")),
    url(r'^admin/', admin.site.urls),
]

apps/app_one/urls.py
from django.conf.urls import url, include
from . import views

# This is app_one
urlpatterns = [
# root route to index method
    url(r'^$', views.index),
    url(r'^main$', views.index, name='index'),
    url(r'^login$', views.login, name='login'),
    url(r'^register$', views.register, name='register'),
    url(r'^logout$', views.logout, name='logout'),

]

apps/app_two/urls.py
#app-level url code:
from django.conf.urls import url, include
from . import views
from django.contrib import admin

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^add_task$', views.add_task, name="add_task"),
    url(r'^edit/(?P<task_id>\d+)$', views.edit, name="edit"),
    url(r'^delete/(?P<task_id>\d+)$', views.delete, name="delete"),

]

apps/app_two/models.py
from django.db import models
from ..app_one.models import *

class Task(models.Model):
    user_link=models.ForeignKey(User, related_name="appts", null=True)
    task_name=models.CharField(max_length=50)
    date=models.DateField(default=datetime.today, blank=True)
    time=models.TimeField()
    status=models.CharField(max_length=10, default="Pending")

apps/app_two/views.py
from django.shortcuts import render, HttpResponse, redirect
from ..app_one.models import User, UserManager
from ..app_two.models import Task
import datetime
from time import strftime
from django.contrib import messages


def index(request):
    print("This is index method in app2 views.py")
    time_now = datetime.datetime.now()
    time_now.strftime('%B %d, %Y %H:%M %p')
    hour_min = time_now.strftime('%H:%M')
    month_day = time_now.strftime('%B %d')
    year = time_now.strftime('%Y')
    full_date = time_now.strftime('%Y-%m-%d')
    if 'user_id' not in request.session:
        return redirect('app1:index')
    else:
        user_id = request.session['user_id']
        this_user = User.objects.get(id=user_id)
        print ("Session user is:", this_user.name)

        todays_date = full_date
        print("Today's date is:", todays_date)

        context = {
            'all_tasks': Task.objects.all().filter(user_link=this_user),
            'hour_min': hour_min,
            'month_day': month_day,
            'year': year,
            # filter by user and date
            # the date filter has to be first, otherwise doesn't work
            'todays_tasks': Task.objects.filter(date=todays_date).filter(user_link=this_user),
            # filter by user and exclude todays_tasks
            'other_tasks': Task.objects.order_by("date").filter(user_link=this_user).exclude(date=todays_date)

        }
    return render(request, 'app_two/index.html', context)


def add_task(request):
    print("This is add_task method in app2 views.py")
# added
    time_now = datetime.datetime.now()
    # get form data
    if request.method == 'POST':
        this_user = User.objects.get(id=request.session['user_id'])
        this_task = request.POST['task_name']
        this_date = request.POST['task_date']
        this_time = request.POST['task_time']

        # check for empty strings
        if (len(this_date) == 0) or (len(this_time) == 0) or (len(this_task) == 0):
            print("Blank form fields")
# error message; redirect
            messages.warning(request, "Form fields must not be left blank")
            return redirect('app2:add_task')

        else:# no blank fields, continuing on ...
            # check that form date isn't in the past
            todays_date = time_now.strftime('%Y-%m-%d')
            if this_date < todays_date:
# error message; redirect
                messages.warning(request, "Your appointment cannot be in the past")
                return redirect('app2:add_task')

            else:
                # checks whether session user has any Task objects
                # if user's task count is 0, creates object, if count > 0, checks through objects in for-loop
                session_user = User.objects.get(id=request.session['user_id'])# get session user
                user_tasks = Task.objects.filter(user_link=session_user)# get session user's tasks
                task_count = user_tasks.count() # counts how many Task objects are linked to session user
                if task_count == 0:
                    print("There are no appointments for this user yet; creating the first one")
                    # create new Task object
                    new_task = Task.objects.create(user_link=this_user, task_name=this_task, date=this_date, time=this_time, status="Pending")
                    return redirect('appointments2:index')

# check for Task object with conflicting date and time
                for task in user_tasks:# checks through Task objects
                    print("task.date is:", task.date, "this_date is", this_date, "task.time is", task.time, "this_time is", this_time)
                    # converts Task object time to same format as form data time, for comparison
                    task_time = task.time.strftime('%H:%M')
                    print("Converted task.time is:", task_time)
                    print("task_time is", task_time, "this_time is", this_time)

                    # compares form data date/time with Task object date/time
                    if str(task.date) == str(this_date) and str(task_time) == str(this_time):
                    # if a match is found
# error message; redirect
                        print("Tasks have the same date and time")
                        messages.warning(request, "You have a conflicting appointment")
                        return redirect('app2:add_task')# stays on form page

                    else:# no conflicting appointment
                        this_task = request.POST['task_name']
                        print("Date is:", this_date, ", Time is:", this_time, ", Task is:", this_task)

                        # create new Task object
                        this_user = User.objects.get(id=request.session['user_id'])
                        new_task = Task.objects.create(user_link=this_user, task_name=this_task, date=this_date, time=this_time, status="Pending")

                        return redirect('app2:index')
    else:# not POST request; redirect to index
        return redirect('app2:index')


# updates Task objects
def edit(request, task_id):
    print("This is edit method in app2 views.py")

    time_now = datetime.datetime.now()# gets datetime object
    hour_min = time_now.strftime('%H:%M')# time for context, html display

    if request.method == 'POST':
# this_task is the existing Task object, not form data
        this_task = Task.objects.get(id=task_id)
        print("Task to edit is:", this_task.task_name, task_id)
        print("Task status is:", this_task.status)
# checks whether Task object's status is Done
# user can't edit task if status is DONE
# check the object status, not the form status
        if this_task.status == "Done":
            print ("STATUS IS DONE")
# error message
# redirect
            messages.warning(request, "You cannot update a finished task")
            return redirect('app2:edit', task_id)

        else: # update Task object
            this_task.name = request.POST['task_name']
            this_task.status = request.POST['status']
            this_task.date = request.POST['task_date']
            this_task.time = request.POST['task_time']
            this_task.save()
            print("Edited task:", this_task.task_name, this_task.status, this_task.date, this_task.time)
            return redirect('app2:index')
    else:
        context = {
            'task': Task.objects.get(id=task_id),
            'hour_min': hour_min,
        }

    return render(request, 'app_two/update.html', context)


def delete(request, task_id):
    print("This is delete method in app2 views.py")
    task_to_delete = Task.objects.get(id=task_id)
    print("Task to delete is:", task_to_delete.task_name, task_id)
    task_to_delete.delete()
    return redirect('app2:index')

apps/app_two/templates/app_two/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'app_two/css/style.css' %}" media="screen" title="no title">
    <title>Appointments</title>
  </head>

  <body>

    <div class = "header">
        <h1 class="one_line">Welcome, {{ request.session.user_alias }}!</h1><a href={% url 'app1:logout' %}>Logout</a>
    </div>

    <div class = "task_table">
      <h3>Here are your appointments for today, {{ month_day }}, {{ year }}:</h3>
      <table>
        <thead>
          <tr>
            <th>Tasks</th>
            <th>Time</th>
            <th>Status</th>
            <th>Action</th>
          </tr>
        </thead>

        <tbody>
          {% for task in todays_tasks %}
            <tr>
              <td>{{ task.task_name }}</td>
              <td>{{ task.time }}</td>
              <td>{{ task.status }}</td>
              <td><a href="{% url 'app2:edit' task_id=task.id %}">Edit<a><a href="{% url 'app2:delete' task_id=task.id %}">Delete<a></td>
          {% endfor %}
        </tbody>
      </table>
    </div><!-- appt_table1 end div -->


    <div class = "task_table">
      <h3>Your other appointments:</h3>
      <table>
        <thead>
          <tr>
            <th>Tasks</th>
            <th>Date</th>
            <th>Time</th>
          </tr>
        </thead>

        <tbody>
          {% for other_task in other_tasks %}
            <tr>
              <td>{{ other_task.task_name }}</td>
              <td>{{ other_task.date }}</td>
              <td>{{ other_task.time }}</td>
          {% endfor %}
        </tbody>
      </table>
    </div><!-- appt_table2 end div -->

    <div class="error_messages">
<!-- displaying error messages -->
      {% if messages %}
        <ul class="messages">
          {% for message in messages %}
            <li>{{ message }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    </div>


    <br>
    <div class = "task_div">
      <h3>Add Appointment</h3>
      <form class="" action="{% url 'app2:add_task' %}" method="POST">
        {% csrf_token %}

      <h3>Date: <input type="date" name="task_date" value=""></h3>
      <h3>Time: <input type="time" name="task_time" value="16:30"></h3>
      <h3>Tasks: <input type="text" name="task_name" value=""></h3>

      <input type="Submit" value="Add">

  </body>
</html>

apps/app_two/templates/app_two/update.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'app_two/css/style.css' %}" media="screen" title="no title">
    <title>Update Appointment</title>
  </head>
  <body>

    <div class = "header2">
        <h1 class="one_line"></h1><a href={% url 'app2:index' %}>Dashboard<a href={% url 'app1:logout' %}>Logout</a></p>
    </div>

    <div class = "task_div">
      <form class="" action="{% url 'app2:edit' task_id=task.id %}" method="POST">
        {% csrf_token %}

      <h3>Tasks: <input type="text" name="task_name" value="{{ task.task_name }}"></h3>

      <h3>Status:<select name="status" value="">
          <option value="Done">Done</option>
          <option value="Pending">Pending</option>
          <option value="Missed">Missed</option>
        </select></h3>

        <div class="error_messages">
    <!-- displaying error messages -->
          {% if messages %}
            <ul class="messages">
              {% for message in messages %}
                <li>{{ message }}</li>
              {% endfor %}
            </ul>
          {% endif %}
        </div>

<!-- displays actual date -->
      <h3>Date: <input type="date" name="task_date" value="{{ task.date|date:"Y-m-d" }}"></h3>
<!-- time displays a valid option -->
      <h3>Time: <input type="time" name="task_time" value="16:30"></h3>

    <div class="update">
      <input type="Submit" value="Update">
    </div>

  </body>
</html>